### ISSUE TITLE
IDE doesn’t work

### ISSUE THREAD

**Issue by laserlab** [ubsuny/g2coral-CP2P2024#2]
https://github.com/ubsuny/g2coral-CP2P2024/blob/91be3515eccd7e23b3f77ead32be8d6236faeaef/.devcontainer/devcontainer.json#L8

I tried to run your codespace and it only starts the default image which is not the expected behavior looking into the devcontainer.json.

**Comment by laserlab** [comment]
This is now just the bare universal container:
```
Using image: mcr.microsoft.com/devcontainers/universal
```
How does that make any sense?

**Comment by AhmedCode99** [comment]
Fixed!
